# Binance Credentials - IMPORTANT: Keep these secure!

BINANCE_KEY = 'iyK0QCtq44CZb7K5BlRcZPCrjn2i7zeL52KQXxs9654NWkQnfQIvm1rKBaNhbXob'
BINANCE_SECRET = 'EowxqqSJr8vD15Bk8oUGArIn9TrYaXlmPjoccV7TVLqLFZ7aqId3KzJY9l5iurOp'
# Trading Configuration
MAX_TRADES_PER_DAY = 4
MAX_TRADES_PER_SYMBOL_PER_DAY = 2
MAX_RISK_PERCENT = 1.0  # 1% of total balance risked on SL

# UI/API Settings
POSITION_UPDATE_INTERVAL = 3
PRICE_UPDATE_INTERVAL = 5